name: coucou_flutter_example
description: Demonstrates how to use the coucou_flutter plugin.

version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  coucou_flutter:
    path: ../

flutter:
  uses-material-design: true