name: coucou_flutter
description: Coucou is a network service discovery and broadcast library for Flutter that supports both Android and iOS.
version: 0.0.3
author: Stefan Mitev <mr.mitew@gmail.com>
homepage: https://github.com/mrmitew/coucou_flutter/
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.mrmitew.coucou.flutter
    pluginClass: CoucouFlutterPlugin